# you can choose themes from $HOME/.config/kitty/kitty-themes/
include ./kitty-themes/Square2.conf

# font_family FantasqueSansM Nerd Font Mono Bold
# font_family VT323
font_family Departure Mono
# font_family Terminus
font_size 12.0
bold_font auto
italic_font auto
bold_italic_font auto

# background_opacity 0.5
# dynamic_background_opacity 1
confirm_os_window_close 0

# Animated cursor
cursor_trail 1

# change to x11 or wayland or leave auto
linux_display_server auto

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 0

# selection_foreground none
# selection_background none

# foreground $ffffff
# background #000000
# cursor #dddddd

enabled_layouts splits

##############################################################

map alt+v launch --location=vsplit
map alt+s launch --location=hsplit

map alt+right neighboring_window right
map alt+l neighboring_window right
map alt+left neighboring_window left
map alt+h neighboring_window left
map alt+up neighboring_window up
map alt+k neighboring_window up
map alt+down neighboring_window down
map alt+j neighboring_window down

map alt+shift+right resize_window wider 5
map alt+shift+l resize_window wider 5

map alt+shift+left resize_window narrower 5
map alt+shift+h resize_window narrower 5

map alt+shift+up resize_window taller 5
map alt+shift+k resize_window taller 5

map alt+shift+down resize_window shorter 5
map alt+shift+j resize_window shorter 5

map alt+shift+= layout_action equalize

map alt+/ scrollback_pager
