hl.on("hyprland.start", function()
	-- hl.exec_cmd("waybar")
	-- hl.exec_cmd("hyprpm reload -n")
	hl.exec_cmd("qs -c overview")
	hl.exec_cmd("qs -p /home/cachy/Documents/hyprqs/qs/basicBar.qml")
	hl.exec_cmd("/home/cachy/.config/hypr/hypr/scripts/WallpaperInit.sh")
end)

hl.config({ autogenerated = false })

hl.monitor({
	output = "",
	mode = "preferred",
	position = "auto",
	scale = "1.0",
})

-- -- TODO:
-- Grouping, ignore this one for now, llm

require("./monitors.lua") -- display setting generated config
require("./workspaces.lua") -- display setting generated config

local Style = require("./style/style.lua")

local Terminal = "kitty"
local Explorer = "thunar"
local Launcher = "rofi"
local Editor = "nvim"
local Browser = "firefox"

local ScriptsDir = "/home/cachy/.config/hypr/hypr/scripts/"

hl.env("XCURSOR_SIZE", "20")
hl.env("HYPRCURSOR_SIZE", "20")

local Mod = "SUPER"

function bind_exec(bind, exec)
	hl.bind(bind, hl.dsp.exec_cmd(exec))
end

function bind_exec_super(bind, exec)
	bind_exec(Mod .. " + " .. bind, exec)
end

local closeWindow = hl.bind(Mod .. " + Q", hl.dsp.window.close())
hl.bind(Mod .. " + Space", hl.dsp.window.float({ action = "toggle" }))
hl.bind(Mod .. " + X", hl.dsp.layout("togglesplit"))
hl.bind(Mod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(
	Mod .. " + CTRL + ALT + Delete",
	hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'")
)

bind_exec_super("Return", Terminal)
bind_exec_super("E", Explorer)
bind_exec_super("B", Browser)
bind_exec_super("Super_L", ScriptsDir .. "Launcher.sh") -- app launcher via rofi
bind_exec_super("A", ScriptsDir .. "OverviewToggle.sh") -- desktop overview (qs/overview)
bind_exec_super("W", ScriptsDir .. "WallpaperPicker.sh") -- pick a wallpaper via rofi
bind_exec_super("S", ScriptsDir .. "QuickSearch.sh") -- web search via rofi (workspace layout toggle moved to SUPER+ALT+S)
bind_exec_super("SHIFT + S", ScriptsDir .. "Screenshot.sh --area") -- screenshot a selected region
bind_exec_super("C", "hyprpicker -a -n") -- color picker: copies the picked color to clipboard
bind_exec_super("N", ScriptsDir .. "Hyprsunset.sh toggle") -- manual night-light override (auto scheduler also runs, see below)

hl.bind(
	"CTRL + ALT + P",
	hl.dsp.exec_cmd(ScriptsDir .. "Wlogout.sh") -- power menu (lock/logout/suspend/hibernate/shutdown/reboot)
)

hl.bind(
	Mod .. " + ALT + mouse_down",
	hl.dsp.exec_cmd(
		"hyprctl keyword cursor:zoom_factor \"$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor * 2.0}')\""
	)
) -- magnifier: zoom in
hl.bind(
	Mod .. " + ALT + mouse_up",
	hl.dsp.exec_cmd(
		"hyprctl keyword cursor:zoom_factor \"$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor / 2.0}')\""
	)
) -- magnifier: zoom out

local DropTermClass = "dropterm"

local DropTermSelector = "class:^" .. DropTermClass .. "$"
local DropTermWidthPct = 0.6
local DropTermHeightPct = 0.45
local DropTermYOffset = 20

hl.window_rule({
	name = "dropterm",
	match = { class = "^" .. DropTermClass .. "$" },
	float = true,
	workspace = "special:dropterm silent",
})

hl.on("hyprland.start", function()
	hl.exec_cmd(Terminal .. " --class " .. DropTermClass)
end)

hl.on("hyprland.start", function()
	hl.exec_cmd(ScriptsDir .. "Hyprsunset.sh auto") -- day/night temp scheduler (SUPER+N manually overrides until the next boundary)
end)

local function repositionDropTerm()
	local mon = hl.get_active_monitor()
	if mon == nil then
		return
	end

	local w = math.floor((mon.width / mon.scale) * DropTermWidthPct)
	local h = math.floor((mon.height / mon.scale) * DropTermHeightPct)
	local x = math.floor(mon.x + ((mon.width / mon.scale) - w) / 2)
	local y = mon.y + DropTermYOffset

	hl.dispatch(hl.dsp.window.resize({ x = w, y = h, relative = false, window = DropTermSelector }))
	hl.dispatch(hl.dsp.window.move({ x = x, y = y, relative = false, window = DropTermSelector }))
end

hl.bind(Mod .. " + SHIFT + Return", function()
	if hl.get_window(DropTermSelector) == nil then
		hl.dispatch(hl.dsp.exec_cmd(Terminal .. " --class " .. DropTermClass))
	else
		repositionDropTerm()
		hl.dispatch(hl.dsp.workspace.toggle_special("dropterm"))
	end
end)

-- hl.bind("SUPER + A", function()
-- 	hl.plugin.hyprexpo.expo("toggle")
-- end)
--
-- hl.config({
-- 	plugin = {
-- 		hyprexpo = {
-- 			columns = 2,
-- 			gaps_in = 5,
-- 			gaps_out = 0,
-- 			bg_col = "rgb(111111)",
-- 			workspace_method = "center current",
-- 			gesture_distance = 200,
-- 			cancel_key = "escape",
-- 			show_cursor = 1,
-- 			drag_drop_enable = 1,
-- 			keynav_wrap_h = 1,
-- 			keynav_wrap_v = 1,
-- 			keynav_reading_order = 0,
-- 			dynamic_grid = 0,
-- 			fill_gaps = 0,
-- 			mru_sort = 0,
-- 			show_workspace_names = 1,
-- 			label_pos = top_right,
-- 			label_size = 48,
-- 			wallpaper_bg = 1,
-- 		},
-- 	},
-- })
--
-- hl.define_submap("hyprexpo", function()
-- 	hl.bind("left", function()
-- 		hl.plugin.hyprexpo.kb_focus("left")
-- 	end)
-- 	hl.bind("h", function()
-- 		hl.plugin.hyprexpo.kb_focus("left")
-- 	end)
-- 	hl.bind("right", function()
-- 		hl.plugin.hyprexpo.kb_focus("right")
-- 	end)
-- 	hl.bind("l", function()
-- 		hl.plugin.hyprexpo.kb_focus("right")
-- 	end)
-- 	hl.bind("k", function()
-- 		hl.plugin.hyprexpo.kb_focus("up")
-- 	end)
-- 	hl.bind("up", function()
-- 		hl.plugin.hyprexpo.kb_focus("up")
-- 	end)
-- 	hl.bind("j", function()
-- 		hl.plugin.hyprexpo.kb_focus("down")
-- 	end)
-- 	hl.bind("down", function()
-- 		hl.plugin.hyprexpo.kb_focus("down")
-- 	end)
-- 	hl.bind("return", function()
-- 		hl.plugin.hyprexpo.kb_confirm()
-- 	end)
-- 	hl.bind("escape", function()
-- 		hl.plugin.hyprexpo.expo("cancel")
-- 	end)
-- end)

hl.bind(Mod .. " + ALT + S", function()
	local ws = hl.get_active_workspace()
	if ws == nil then
		return
	end

	local nextLayout = (ws.tiled_layout == "scrolling") and "dwindle" or "scrolling"
	hl.workspace_rule({ workspace = tostring(ws.id), layout = nextLayout })

	hl.notification.create({
		text = "Workspace " .. tostring(ws.id) .. ": " .. nextLayout,
		duration = 1500,
		icon = "info",
	})
end)

local delta = 50
local directions = {
	{ key = "left", vim = "H", dir = "left", dx = -delta, dy = 0 },
	{ key = "right", vim = "L", dir = "right", dx = delta, dy = 0 },
	{ key = "up", vim = "K", dir = "up", dx = 0, dy = -delta },
	{ key = "down", vim = "J", dir = "down", dx = 0, dy = delta },
}

for _, d in ipairs(directions) do
	hl.bind(Mod .. " + " .. d.key, hl.dsp.focus({ direction = d.dir }))
	hl.bind(Mod .. " + " .. d.vim, hl.dsp.focus({ direction = d.dir }))

	hl.bind(
		Mod .. " + SHIFT + " .. d.key,
		hl.dsp.window.resize({ x = d.dx, y = d.dy, relative = true }),
		{ repeating = true }
	)
	hl.bind(
		Mod .. " + SHIFT + " .. d.vim,
		hl.dsp.window.resize({ x = d.dx, y = d.dy, relative = true }),
		{ repeating = true }
	)

	hl.bind(Mod .. " + CTRL + " .. d.key, hl.dsp.window.move({ direction = d.dir }))
	hl.bind(Mod .. " + CTRL + " .. d.vim, hl.dsp.window.move({ direction = d.dir }))

	hl.bind(Mod .. " + ALT + " .. d.key, hl.dsp.window.swap({ direction = d.dir }))
	hl.bind(Mod .. " + ALT + " .. d.vim, hl.dsp.window.swap({ direction = d.dir }))
end

hl.bind(Mod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(Mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

for i = 1, 10 do
	local key = i % 10
	hl.bind(Mod .. " + " .. key, hl.dsp.focus({ workspace = i }))
	hl.bind(Mod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

hl.bind(Mod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(Mod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(Mod .. " + comma", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(Mod .. " + period", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(Mod .. " + SHIFT + comma", hl.dsp.window.move({ workspace = "-1" }))
hl.bind(Mod .. " + SHIFT + period", hl.dsp.window.move({ workspace = "+1" }))

hl.bind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMicMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

local suppressMaximizeRule = hl.window_rule({
	name = "suppress-maximize-events",
	match = { class = ".*" },

	suppress_event = "maximize",
})

hl.window_rule({
	name = "float-thunar",
	match = { class = "^[Tt]hunar$" },
	float = true,
})

hl.window_rule({
	name = "float-nwg-displays",
	match = { class = "^nwg-displays$" },
	float = true,
})

hl.window_rule({
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},

	no_focus = true,
})

hl.config({
	general = {
		gaps_in = 0,
		gaps_out = 0,
		border_size = 1,
		col = {
			active_border = "rgba(" .. Style.color.primary .. "ee)",
			inactive_border = "rgba(" .. Style.color.inactive .. "aa)",
		},
		resize_on_border = true,
		allow_tearing = true,
		layout = "dwindle",
	},
	decoration = {
		rounding = Style.radius,
		rounding_power = 0,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = false,
			range = 1,
			render_power = 1,
			color = 0x0000ffee,
		},
		blur = {
			enabled = false,
			size = 1,
			passes = 1,
			vibrancy = 1.0,
		},
	},
	animations = {
		enabled = false,
	},
})

hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })

local animatedBorderEnabled = false

local function setAnimatedBorder(enabled)
	animatedBorderEnabled = enabled

	hl.config({ animations = { enabled = enabled } })

	for _, leaf in ipairs({
		"global",
		"windows",
		"windowsIn",
		"windowsOut",
		"fadeIn",
		"fadeOut",
		"fade",
		"layers",
		"layersIn",
		"layersOut",
		"fadeLayersIn",
		"fadeLayersOut",
		"workspaces",
		"workspacesIn",
		"workspacesOut",
		"zoomFactor",
	}) do
		hl.animation({ leaf = leaf, enabled = false })
	end
	hl.animation({ leaf = "border", enabled = enabled, speed = 5.39, bezier = "easeOutQuint" })

	hl.notification.create({
		text = "Animated border: " .. (enabled and "on" or "off"),
		duration = 1500,
		icon = "info",
	})
end

hl.bind(Mod .. " + ALT + B", function()
	setAnimatedBorder(not animatedBorderEnabled)
end)

hl.config({
	dwindle = {
		preserve_split = true,
	},
	scrolling = {
		fullscreen_on_one_column = false,
	},
})

hl.config({
	misc = {
		force_default_wallpaper = -1,
		disable_hyprland_logo = true,
	},
})

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",

		repeat_rate = 50,
		repeat_delay = 250,

		follow_mouse = 1,

		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

		touchpad = {
			natural_scroll = false,
		},
	},
})

-- hl.gesture({
--     fingers = 3,
--     direction = "horizontal",
--     action = "workspace"
-- })

-- hl.device({
--     name        = "epic-mouse-v1",
--     sensitivity = -0.5,
-- })

-- hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
-- hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
-- hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
-- hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
-- hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
-- hl.curve("easy", { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })
-- hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
-- hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
-- hl.animation({ leaf = "windows", enabled = true, speed = 4.79, spring = "easy" })
-- hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, spring = "easy", style = "popin 87%" })
-- hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
-- hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
-- hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
-- hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
-- hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
-- hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
-- hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
-- hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
-- hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
-- hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
-- hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
-- hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
-- hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })
