local script_dir = debug.getinfo(1, "S").source:match("^@(.*/)")

hl.on("hyprland.start", function()
	-- hl.exec_cmd("waybar")
	-- hl.exec_cmd("hyprpm reload -n")
	hl.exec_cmd("qs -p " .. script_dir .. "qs/overview")
	hl.exec_cmd("qs -p " .. script_dir .. "qs/basicBar.qml")
	hl.exec_cmd(script_dir .. "hypr/scripts/WallpaperInit.sh")
	hl.exec_cmd("wl-paste --watch cliphist store")
	hl.exec_cmd("systemctl --user enable --now opentabletdriver")
end)

hl.config({ autogenerated = false })

hl.monitor({
	output = "",
	mode = "preferred",
	position = "auto",
	scale = "1.0",
})

require("monitors")
require("workspaces")

local Style = dofile(script_dir .. "style/style.lua")

local Terminal = "kitty"
local Explorer = "thunar"
local Launcher = "rofi"
local Editor = "nvim"
local Browser = "firefox"

local ScriptsDir = script_dir .. "hypr/scripts/"

hl.env("XCURSOR_SIZE", "20")
hl.env("HYPRCURSOR_SIZE", "20")

local Mod = "SUPER"

function bind_exec(bind, exec)
	hl.bind(bind, hl.dsp.exec_cmd(exec))
end

function bind_exec_super(bind, exec)
	bind_exec(Mod .. " + " .. bind, exec)
end

local closeWindow = hl.bind(Mod .. " + Q", hl.dsp.window.close())
hl.bind(Mod .. " + Space", hl.dsp.window.float({ action = "toggle" }))
hl.bind(Mod .. " + X", hl.dsp.layout("togglesplit"))
hl.bind(Mod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(
	Mod .. " + CTRL + ALT + Delete",
	hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'")
)

bind_exec_super("Return", Terminal)
bind_exec_super("E", Explorer)
bind_exec_super("B", Browser)
bind_exec_super("V", "kitty nvim")
bind_exec_super("Super_L", ScriptsDir .. "Launcher.sh")
bind_exec_super("A", ScriptsDir .. "OverviewToggle.sh")
bind_exec_super("W", ScriptsDir .. "WallpaperPicker.sh")
bind_exec_super("S", ScriptsDir .. "QuickSearch.sh")
bind_exec_super("SHIFT + S", ScriptsDir .. "Screenshot.sh --area")
bind_exec_super("C", "hyprpicker -a -n")
bind_exec_super("N", ScriptsDir .. "Hyprsunset.sh toggle")
bind_exec_super("ALT + V", ScriptsDir .. "ClipManager.sh")

hl.bind("CTRL + ALT + P", hl.dsp.exec_cmd(ScriptsDir .. "Wlogout.sh"))

hl.bind("CTRL + ALT + Escape", hl.dsp.exec_cmd("pkill -9 rofi"), { locked = true })

local function setZoomFactor(multiplier)
	local factor = hl.get_config("cursor:zoom_factor")
	if factor < 1 then
		factor = 1
	end
	hl.config({ cursor = { zoom_factor = factor * multiplier } })
end

hl.bind(Mod .. " + ALT + mouse_up", function()
	setZoomFactor(2.0)
end) -- magnifier: zoom in
hl.bind(Mod .. " + ALT + mouse_down", function()
	setZoomFactor(0.5)
end) -- magnifier: zoom out

hl.config({ binds = { scroll_event_delay = 0, workspace_back_and_forth = true } })

local DropTermClass = "dropterm"

local DropTermSelector = "class:^" .. DropTermClass .. "$"
local DropTermWidthPct = 0.75
local DropTermHeightPct = 0.5
local DropTermYOffset = 0.05
local DropTermStash = "special:dropterm_stash"

hl.window_rule({
	name = "dropterm",
	match = { class = "^" .. DropTermClass .. "$" },
	float = true,
	workspace = DropTermStash .. " silent",
	size = string.format("%d%% %d%%", DropTermWidthPct * 100, DropTermHeightPct * 100),
})

hl.on("hyprland.start", function()
	hl.exec_cmd(Terminal .. " --class " .. DropTermClass)
end)

hl.on("hyprland.start", function()
	hl.exec_cmd(ScriptsDir .. "Hyprsunset.sh auto")
end)

local function repositionDropTerm()
	local mon = hl.get_active_monitor()
	if mon == nil then
		return
	end

	local w = math.floor((mon.width / mon.scale) * DropTermWidthPct)
	local h = math.floor((mon.height / mon.scale) * DropTermHeightPct)
	local x = math.floor(mon.x + ((mon.width / mon.scale) - w) / 2)
	local y = math.floor(mon.y + ((mon.height / mon.scale) * DropTermYOffset))

	hl.dispatch(hl.dsp.window.resize({ x = w, y = h, relative = false, window = DropTermSelector }))
	hl.dispatch(hl.dsp.window.move({ x = x, y = y, relative = false, window = DropTermSelector }))
end

local function showDropTerm()
	local activeWs = hl.get_active_workspace()
	if activeWs == nil then
		return
	end

	hl.dispatch(hl.dsp.window.move({ workspace = activeWs, follow = false, window = DropTermSelector }))
	hl.dispatch(hl.dsp.window.float({ action = "enable", window = DropTermSelector }))
	repositionDropTerm()
	hl.dispatch(hl.dsp.focus({ window = DropTermSelector }))
end

local dropTermOpenSub = nil

hl.bind(Mod .. " + SHIFT + Return", function()
	local term = hl.get_window(DropTermSelector)
	if term == nil then
		if dropTermOpenSub == nil then
			dropTermOpenSub = hl.on("window.open", function(win)
				if win == nil or win.class ~= DropTermClass then
					return
				end
				dropTermOpenSub:remove()
				dropTermOpenSub = nil
				showDropTerm()
			end)
		end
		hl.dispatch(hl.dsp.exec_cmd(Terminal .. " --class " .. DropTermClass))
		return
	end

	local activeWs = hl.get_active_workspace()
	if activeWs ~= nil and term.workspace ~= nil and term.workspace.id == activeWs.id then
		hl.dispatch(hl.dsp.window.move({ workspace = DropTermStash, follow = false, window = DropTermSelector }))
	else
		showDropTerm()
	end
end)

hl.bind(Mod .. " + ALT + S", function()
	local ws = hl.get_active_workspace()
	if ws == nil then
		return
	end

	local nextLayout = (ws.tiled_layout == "scrolling") and "dwindle" or "scrolling"
	hl.workspace_rule({ workspace = tostring(ws.id), layout = nextLayout })

	hl.notification.create({
		text = "Workspace " .. tostring(ws.id) .. ": " .. nextLayout,
		duration = 1500,
		icon = "info",
	})
end)

local delta = 50
local directions = {
	{ key = "left", vim = "H", dir = "left", dx = -delta, dy = 0 },
	{ key = "right", vim = "L", dir = "right", dx = delta, dy = 0 },
	{ key = "up", vim = "K", dir = "up", dx = 0, dy = -delta },
	{ key = "down", vim = "J", dir = "down", dx = 0, dy = delta },
}

for _, d in ipairs(directions) do
	hl.bind(Mod .. " + " .. d.key, hl.dsp.focus({ direction = d.dir }))
	hl.bind(Mod .. " + " .. d.vim, hl.dsp.focus({ direction = d.dir }))

	hl.bind(
		Mod .. " + SHIFT + " .. d.key,
		hl.dsp.window.resize({ x = d.dx, y = d.dy, relative = true }),
		{ repeating = true }
	)
	hl.bind(
		Mod .. " + SHIFT + " .. d.vim,
		hl.dsp.window.resize({ x = d.dx, y = d.dy, relative = true }),
		{ repeating = true }
	)

	hl.bind(Mod .. " + CTRL + " .. d.key, hl.dsp.window.move({ direction = d.dir }))
	hl.bind(Mod .. " + CTRL + " .. d.vim, hl.dsp.window.move({ direction = d.dir }))

	hl.bind(Mod .. " + ALT + " .. d.key, hl.dsp.window.swap({ direction = d.dir }))
	hl.bind(Mod .. " + ALT + " .. d.vim, hl.dsp.window.swap({ direction = d.dir }))
end

local RepeatInitialDelay = 240
local RepeatInterval = 60

local function bindRepeatable(keys, dispatcher)
	local timer = nil

	local function fire()
		hl.dispatch(dispatcher)
	end

	hl.bind(keys, function()
		fire()
		timer = hl.timer(function()
			fire()
			if timer ~= nil then
				timer:set_timeout(RepeatInterval)
			end
		end, { timeout = RepeatInitialDelay, type = "repeat" })
	end)

	hl.bind(keys, function()
		if timer ~= nil then
			timer:set_enabled(false)
			timer = nil
		end
	end, { release = true })
end

hl.bind(Mod .. " + G", hl.dsp.group.toggle())
bindRepeatable(Mod .. " + bracketleft", hl.dsp.group.prev())
bindRepeatable(Mod .. " + bracketright", hl.dsp.group.next())
hl.bind(Mod .. " + SHIFT + Space", hl.dsp.window.move({ out_of_group = true }))

hl.bind(Mod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(Mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

for i = 1, 10 do
	local key = i % 10
	hl.bind(Mod .. " + " .. key, hl.dsp.focus({ workspace = i }))
	hl.bind(Mod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

hl.bind(Mod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(Mod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

bindRepeatable(Mod .. " + comma", hl.dsp.focus({ workspace = "e-1" }))
bindRepeatable(Mod .. " + period", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(Mod .. " + SHIFT + comma", hl.dsp.window.move({ workspace = "-1" }))
hl.bind(Mod .. " + SHIFT + period", hl.dsp.window.move({ workspace = "+1" }))

hl.bind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMicMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

local suppressMaximizeRule = hl.window_rule({
	name = "suppress-maximize-events",
	match = { class = ".*" },

	suppress_event = "maximize",
})

hl.window_rule({
	name = "float-thunar",
	match = { class = "^[Tt]hunar$" },
	float = true,
})

hl.window_rule({
	name = "float-nwg-displays",
	match = { class = "^nwg-displays$" },
	float = true,
})

hl.window_rule({
	name = "firefox-full-opacity",
	match = { class = "^" .. Browser .. "$" },
	opacity = "1.0 override 1.0 override",
})

hl.window_rule({
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},

	no_focus = true,
})

hl.config({
	general = {
		gaps_in = 0,
		gaps_out = 0,
		border_size = 1,
		col = {
			active_border = "rgba(" .. Style.color.primary .. "ee)",
			inactive_border = "rgba(" .. Style.color.inactive .. "aa)",
		},
		resize_on_border = true,
		allow_tearing = true,
		layout = "dwindle",
	},
	decoration = {
		rounding = Style.radius,
		rounding_power = 0,
		active_opacity = 1.0,
		inactive_opacity = 0.9,
		shadow = {
			enabled = false,
			range = 1,
			render_power = 1,
			color = 0x0000ffee,
		},
		blur = {
			enabled = false,
			size = 1,
			passes = 1,
			vibrancy = 1.0,
		},
	},
	animations = {
		enabled = false,
	},
})

hl.config({
	dwindle = {
		preserve_split = true,
	},
	scrolling = {
		fullscreen_on_one_column = false,
	},
})

hl.config({
	misc = {
		force_default_wallpaper = -1,
		disable_hyprland_logo = true,
	},
})

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",

		repeat_rate = 50,
		repeat_delay = 250,

		follow_mouse = 1,

		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

		touchpad = {
			natural_scroll = false,
		},
	},
})

-- hl.gesture({
--     fingers = 3,
--     direction = "horizontal",
--     action = "workspace"
-- })

-- hl.device({
--     name        = "epic-mouse-v1",
--     sensitivity = -0.5,
-- })

-- hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
-- hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
-- hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
-- hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
-- hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
-- hl.curve("easy", { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })
-- hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
-- hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
-- hl.animation({ leaf = "windows", enabled = true, speed = 4.79, spring = "easy" })
-- hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, spring = "easy", style = "popin 87%" })
-- hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
-- hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
-- hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
-- hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
-- hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
-- hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
-- hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
-- hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
-- hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
-- hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
-- hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
-- hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
-- hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })
