-- Generated by nwg-displays on 2026-08-25 at 21:43:22. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "3840x2160@60.0",
    position = "1920x360",
    scale = 1.2000000000000002
})
hl.monitor({
    output = "HDMI-A-3",
    mode = "1920x1080@60.0",
    position = "0x1080",
    scale = 1.0
})
