<<<<<<< HEAD
-- Generated by nwg-displays on 2026-09-02 at 17:57:11. Do not edit manually.
=======
-- Generated by nwg-displays on 2026-08-25 at 21:43:22. Do not edit manually.
>>>>>>> 08fa1985e0d9b9b5fd5a1b0af4c40ad419939a14

hl.monitor({
    output = "DP-1",
    mode = "3840x2160@60.0",
    position = "1920x360",
    scale = 1.2000000000000002
})
hl.monitor({
<<<<<<< HEAD
    output = "HDMI-A-2",
    mode = "3840x2160@30.0",
    position = "1920x0",
    scale = 1.0,
    mirror = "eDP-1"
=======
    output = "HDMI-A-3",
    mode = "1920x1080@60.0",
    position = "0x1080",
    scale = 1.0
>>>>>>> 08fa1985e0d9b9b5fd5a1b0af4c40ad419939a14
})
