-- Generated by nwg-displays on 2026-08-20 at 11:37:10. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "3840x2160@60.0",
    position = "1920x720",
    scale = 1.5000000000000004
})
hl.monitor({
    output = "HDMI-A-2",
    mode = "1920x1080@60.0",
    position = "4480x1080",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-3",
    mode = "1920x1080@60.0",
    position = "0x1080",
    scale = 1.0
})
