-- Central style loader for hyprland.lua.
--
-- Reads style/style.json (the single source of truth also consumed by
-- qs/theme/Palette.qml and hypr/rofi/colors.rasi, generated by
-- hypr/scripts/GenerateRofiColors.sh) and returns it as a plain Lua table.
--
-- Colors are exposed as bare 6-digit hex strings (no "#", no alpha), e.g.
-- "89b4fa" — format them per call site, e.g.:
--   col = { active_border = "rgba(" .. Style.colors.accent .. "ee)" }

-- Resolved via debug info (not require()) so this doesn't depend on how
-- hyprland.lua's custom require() shim resolves nested relative paths.
local script_dir = debug.getinfo(1, "S").source:match("^@(.*/)")
local json = dofile(script_dir .. "lib/json.lua")

local file = assert(io.open(script_dir .. "style.json", "r"))
local contents = file:read("*a")
file:close()

return json.decode(contents)
