# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EDEEE7
background         #1F1F1D
cursor             #C2C0A0

active_tab_foreground     #1F1F1D
active_tab_background     #EDEEE7
inactive_tab_foreground   #EDEEE7
inactive_tab_background   #1F1F1D

active_border_color   #EDEEE7
inactive_border_color #1F1F1D
bell_border_color     #464722

color0      #454643
color1		#464722
color2		#716E42
color3		#716E42
color4		#716E42
color5		#716E42
color6		#999B8C
color7		#DDDED5
color8		#9B9B95
color9		#5D5F2E
color10		#979358
color11		#979358
color12		#979358
color13		#979358
color14		#CCCEBB
color15		#DDDED5
