# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1F1F1D)
$foreground = rgb(EDEEE7)
$color0 = rgb(454643)
$color1 = rgb(464722)
$color2 = rgb(716E42)
$color3 = rgb(716E42)
$color4 = rgb(716E42)
$color5 = rgb(716E42)
$color6 = rgb(999B8C)
$color7 = rgb(DDDED5)
$color8 = rgb(9B9B95)
$color9 = rgb(5D5F2E)
$color10 = rgb(979358)
$color11 = rgb(979358)
$color12 = rgb(979358)
$color13 = rgb(979358)
$color14 = rgb(CCCEBB)
$color15 = rgb(DDDED5)
