pragma Singleton
import QtQuick
import Quickshell.Io

// Central colors/fonts/radius/spacing, shared with hyprland.lua
// (style/style.lua) and the rofi menus (hypr/rofi/colors.rasi, generated by
// hypr/scripts/GenerateRofiColors.sh). Reads style/style.json directly and
// live-reloads on change, so editing that file updates the bar (and any
// other quickshell UI built against this) without a restart.
//
// Defaults below match style/style.json and only matter until it loads (or
// if it fails to load).
QtObject {
	id: root

	property QtObject color: QtObject {
		property color primary: "#0000ee"
		property color secondary: "#33008b"
		property color danger: "#ff4c4c"
		property color warning: "#ffcc00"
		property color ok: "#4caf50"
		property color active: "#dddddd"
		property color inactive: "#a0a0a0"
		property color background: "#ffffff"
		property color background_light: "#e0e0e0"
		property color background_dark: "#c0c0c0"
		property color border: "#eeeeee"
		property color border_light: "#add8e6"
		property color border_dark: "#7777ea"
		property color text: "#555555"
		property color text_secondary: "#a0a0a0"
		property color text_light: "#ffffff"
		property color text_dark: "#555555"
	}

	property QtObject font: QtObject {
		property string family: "Monospace"
		property int size: 12
	}

	property int radius: 10

	property QtObject spacing: QtObject {
		property int gap: 5
		property int padding: 10
	}

	property FileView _file: FileView {
		// Quickshell sandboxes relative path/import resolution to within the
		// qs/ config root, so a repo-root file needs an absolute path here
		// (matching how basicBar.qml itself is launched via an absolute
		// path in hyprland.lua rather than a quickshell-registered config).
		path: "/home/cachy/Documents/hyprqs/style/style.json"
		watchChanges: true
		onFileChanged: reload()
		onLoaded: {
			try {
				root._apply(JSON.parse(text()))
			} catch (e) {
				console.warn("Palette: failed to parse style/style.json:", e)
			}
		}
		onLoadFailed: error => console.warn("Palette: failed to load style/style.json:", error)
	}

	function _apply(data) {
		if (data.color) {
			for (const key in data.color) {
				if (root.color.hasOwnProperty(key)) {
					root.color[key] = "#" + data.color[key]
				}
			}
		}
		if (data.font) {
			if (data.font.family)
				root.font.family = data.font.family
			if (data.font.size)
				root.font.size = data.font.size
		}
		if (data.radius !== undefined)
			root.radius = data.radius
		if (data.spacing) {
			if (data.spacing.gap !== undefined)
				root.spacing.gap = data.spacing.gap
			if (data.spacing.padding !== undefined)
				root.spacing.padding = data.spacing.padding
		}
	}
}
