[general]
bars = 16
framerate = 30
autosens = 1

[input]
method = pulse
source = alsa_output.usb-Blue_Microphones_Yeti_Stereo_Microphone_REV8-00.analog-stereo.monitor

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 100
